openapi: 3.0.3
info:
  title: OttoMate API
  description: Lean automation tool API for Make.com workflows
  version: 1.0.0
  contact:
    name: OttoMate
    
servers:
  - url: https://ottomate-dev-[hash].a.run.app
    description: Production server
  - url: http://localhost:8080
    description: Local development

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns service health status
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  timestamp:
                    type: string
                    format: date-time
                    
  /schema:
    get:
      summary: Get Blueprint JSON Schema
      description: Returns the Blueprint schema for validation
      responses:
        '200':
          description: Blueprint schema
          content:
            application/json:
              schema:
                type: object
                description: JSON Schema for automation blueprints
                
  /lint:
    post:
      summary: Validate automation blueprint
      description: Validates a blueprint against lint rules
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Blueprint'
      responses:
        '200':
          description: Validation results
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        rule:
                          type: string
                        message:
                          type: string
                        path:
                          type: string
                          
  /briefs:
    get:
      summary: List automation briefs
      description: Get all automation briefs
      responses:
        '200':
          description: List of briefs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Blueprint'
    post:
      summary: Create automation brief
      description: Create a new automation brief
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Blueprint'
      responses:
        '201':
          description: Brief created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  status:
                    type: string
                    
  /briefs/{id}:
    get:
      summary: Get specific brief
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Brief details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blueprint'
                
  /jobs:
    get:
      summary: List automation jobs
      description: Get running/completed jobs
      responses:
        '200':
          description: List of jobs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    brief_id:
                      type: string
                    status:
                      type: string
                      enum: [pending, running, completed, failed]
                    created_at:
                      type: string
                      format: date-time
                      
  /export:
    post:
      summary: Export automation to Make.com
      description: Convert blueprint to Make.com format
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                brief_id:
                  type: string
                format:
                  type: string
                  enum: [make_json, make_blueprint]
      responses:
        '200':
          description: Exported automation
          content:
            application/json:
              schema:
                type: object
                properties:
                  export_data:
                    type: object
                  format:
                    type: string

components:
  schemas:
    Blueprint:
      type: object
      required: [name, version, trigger, actions]
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          maxLength: 500
        version:
          type: string
          pattern: '^\\d+\\.\\d+\\.\\d+$'
        trigger:
          type: object
          required: [type, app]
          properties:
            type:
              type: string
              enum: [webhook, schedule, email, file_watch, form_submit, api_call]
            app:
              type: string
            config:
              type: object
        actions:
          type: array
          minItems: 1
          items:
            type: object
            required: [id, type, app]
            properties:
              id:
                type: string
                pattern: '^[a-zA-Z0-9_-]+$'
              type:
                type: string
                enum: [create, update, delete, send, get, transform, condition, delay]
              app:
                type: string
              config:
                type: object
              condition:
                type: object
              depends_on:
                type: array
                items:
                  type: string
        error_handling:
          type: object
        schedule:
          type: object
        tags:
          type: array
          items:
            type: string
